CREATE DATABASE Library;

USE Library;

CREATE TABLE Genre (
Genre_ID INT NOT NULL PRIMARY KEY,
GName VARCHAR(50) NOT NULL,
GDescription VARCHAR(255) NOT NULL
);

CREATE TABLE Catalog (
Catalog_ID INT NOT NULL PRIMARY KEY,
CName VARCHAR(50) NOT NULL,
Location VARCHAR(50) NOT NULL
);

CREATE TABLE Author (
Author_ID INT NOT NULL PRIMARY KEY,
AName VARCHAR(50) NOT NULL,
Birth_Date DATE,
Nationality VARCHAR(50)
);

CREATE TABLE LMember (
Member_ID INT NOT NULL PRIMARY KEY,
MName VARCHAR(50) NOT NULL,
Contact_Info VARCHAR(50) NOT NULL,
Join_Date DATE NOT NULL
);

CREATE TABLE Staff (
Staff_ID INT NOT NULL PRIMARY KEY,
SName VARCHAR(50) NOT NULL,
Contact_Info VARCHAR(50) NOT NULL,
Job_Title VARCHAR(50) NOT NULL,
Hire_Date DATE NOT NULL
);

CREATE TABLE Material (
Material_ID INT NOT NULL PRIMARY KEY, 
Title VARCHAR(128) NOT NULL,
Publication_Date DATE NOT NULL,
Catalog_ID INT,
Genre_ID INT,
FOREIGN KEY(Catalog_ID) REFERENCES Catalog(Catalog_ID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(Genre_ID) REFERENCES Genre(Genre_ID) ON DELETE SET NULL ON UPDATE CASCADE 
);

CREATE TABLE Authorship (
Authorship_ID INT NOT NULL PRIMARY KEY,
Author_ID INT,
Material_ID INT,
FOREIGN KEY(Author_ID) REFERENCES Author(Author_ID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(Material_ID) REFERENCES Material(Material_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Borrow (
Borrow_ID INT NOT NULL PRIMARY KEY, 
Material_ID INT, 
Member_ID INT,
Staff_ID INT, 
Borrow_Date DATE NOT NULL,
Due_Date DATE NOT NULL,
Return_Date DATE, 
FOREIGN KEY(Material_ID) REFERENCES Material(Material_ID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(Member_ID) REFERENCES LMember(Member_ID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID) ON DELETE SET NULL ON UPDATE CASCADE
);